[workspace]
resolver = "3"
members = ["must-hop", "libloragw-sys", "loragw", "must-gw"]
exclude = [
  "examples/ble/esp32c6",
  "examples/lora/rak3272s",
  "examples/gateway/sx1302",
]


[profile.dev]
opt-level = "s"

[profile.release]
debug = true
