[default.probe]
# The chip you are using
chip = "esp32c6"
# USB-JTAG-Serial often needs a lower speed to be stable initially
speed = 1000

[default.rtt]
# This is the critical line missing from your setup
enabled = true

[default.gdb]
enabled = false
