[package]
name = "loragw"
version = "0.1.0"
edition = "2024"

[dependencies]
libloragw-sys = { path = "../libloragw-sys" }
toml = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
